.TH DWM 1 DWM\-VERSION
.SH NAME
DWM \- Dynamic Window Manager
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
DWM is a dynamic window manager for X. The 'Orange' version diviation is a
heavily modified fork that has taken on a life of its own while staying true to
the spirit of the original - simple, fast, secure. It manages windows in tiled,
monocle and floating layouts. Either layout can be applied dynamically,
optimising the environment for the application in use and the task performed.
.P
In tiled layout windows are managed in a master and stacking area. The master
area contains one window by default, and the stacking area contains all other
windows. The number of master area windows can be adjusted from zero to an
arbitrary number. Master and stack areas, as well as open windows belonging
to them can be moved or rotated around in any direction dynamically. In monocle
layout all windows are maximised to the screen size. In floating layout windows
can be resized and moved freely. Dialog windows are always managed floating,
regardless of the layout applied.
.P
Windows are grouped by tags. Each window can be tagged with one or multiple
tags. Selecting certain tags displays all windows with these tags.
.P
Each screen contains a small status bar which displays all available tags,
user@hostname, the title of the focused window, attach direction indicator,
the layout, the keyboard layout, easy access button to this manual, 'warp on
focus' status/toggle button, 'view on tag' function status/toggle button, 'keyboard
lock' status/toggle button and the 'power' button. A floating window is indicated
with an empty square and a fixed floating window is indicated with a filled
square before the windows title. Another empty square below the first one indicates
that the window has 'isfakefullscreen' rule set (only allows the window to
fullscreen into space currently given to it;) the square is filled if the fullscreen
window is currently fullscreen. The third square indicates that the window has
'ispermanent' rule set (disallows closing of the window by DWM.) The selected tags
are indicated with a different color. The tags of the focused window are indicated
with a filled square in the top left corner.  The tags which are applied to one or
more windows are indicated with an empty square in the top left corner.
.P
Additionally a screen may contain a small (extra) status bar if it is enabled (default),
and the screen is currently focused or has the 'system tray' pinned to it. This bar displays 
text read from the root window name property (xsetroot -name 'text') and the aformentioned
'system tray,' built into DWM to accomodate programs that can be minimized to tray.
.P
DWM draws a small border around windows to indicate the focus/urgency state.
.SH OPTIONS
.TP
.B \-v
prints version information to standard output, then exits.
.SH USAGE(Keyboard)
.SS Main commands
.TP
.B WinKey\-F1
Open manual page for
.BR dwm(1).
.TP
.B WinKey\-Return
Spawn
.BR st(1).
.TP
.B WinKey\-Backspace
Spawn
.BR dmenu(1)
for launching other programs.
.TP
.B WinKey\-ESC
Kill the currently focused window.
.TP
.B WinKey\-Shift\-ESC
Kill all unfocused windows on the focused screen.
.TP
.B WinKey\-Control\-ESC
Open 'shutdown' menu.
.TP
.B WinKey\-Control\-Shift\-ESC
Kill
.BR dwm(1).
.TP
.B WinKey\-Home
Toggle keyboard lock (disable all shortcuts except 'quit' and 'toggle keyboard lock.')
.SS Window functions
.TP
.B WinKey\-Space
Toggle focused window between tiled and floating state.
.TP
.B WinKey\-Shift\-f
Toggle focused window native fullscreen mode if available.
.TP
.B WinKey\-Control\-f
Force focused window into pseudo fullscreen mode.
.TP
.B WinKey\-Control\-Shift\-f
Toggle 'isfakefullscreen' rule for the focused window.
.TP
.B WinKey\-Control\-Shift\-Space
Toggle 'ispermanent' rule for the focused window.
.TP
.B WinKey\-j
Focus previous window on the focused screen.
.TP
.B WinKey\-Shift\-j
Push the focused window into the previous spot on the focused screen.
.TP
.B WinKey\-k
Focus next window on the focused screen.
.TP
.B WinKey\-Shift\-j
Push the focused window into the next spot on the focused screen.
.TP
.B WinKey\-q
Focus the last focused window on the focused screen.
.TP
.B WinKey\-Shift\-q
Push the focused window into the spot of the last focused window on the focused screen.
.TP
.B WinKey\-w
Focus the window in the first spot.
.TP
.B WinKey\-Shift\-w
Push the focused window into the first spot.
.TP
.B WinKey\-a
Focus the window in the second spot.
.TP
.B WinKey\-Shift\-a
Push the focused window into the second spot.
.TP
.B WinKey\-z
Focus the window in the third spot.
.TP
.B WinKey\-Shift\-z
Push the focused window into the third spot.
.TP
.B WinKey\-x
Focus the window in the last spot.
.TP
.B WinKey\-Shift\-x
Push the focused window into the last spot.
.TP
.B WinKey\-Shift\-d
Toggle next 'attach direction' for the selected screen.
.TP
.B WinKey\-Control\-d
Toggle previous 'attach direction' for the selected screen.
.TP
.B WinKey\-Control\-Shift\-d
Set 'attach direction' to default for the selected screen.
.TP
.B WinKey\-c
Toggle 'warp on focus' function (warps pointer to the center of the focused window when on.)
.SS Layout functions
.TP
.B WinKey\-`
Switch to the last used layout.
.TP
.B WinKey\-Shift\-`
Switch to next layout.
.TP
.B WinKey\-Control\-`
Switch to previous layout.
.TP
.B WinKey\-Shift\-Control\-f
Toggle monocle layout.
.SS Tiled layout manipulation functions.
.TP
.B WinKey\-Shift\-n
Increase 'nmaster' by 1 in 'tiled' layout.
.TP
.B WinKey\-Control\-n
Decrease 'nmaster' by 1 in 'tiled' layout.
.TP
.B WinKey\-r
Move master area around the screen in clockwise direction.
.TP
.B WinKey\-Shift\-r
Toggle the alignment of windows in master area between vertical and horizontal.
.TP
.B WinKey\-Control\-r
Toggle the alignment of windows in stack area between vertical and horizontal.
.TP
.B WinKey\-Control\-Shift\-r
Execute all 3 'tiled' layout (listed above) manipulation functions at once.
.TP
.B WinKey\-h
Decrease size of the master area.
.TP
.B WinKey\-Shift\-h
Decrease size of windowd in the master area.
.TP
.B WinKey\-Control\-h
Decrease size of windowd in the stack area.
.TP
.B WinKey\-Control\-Shift\-h
Execute all 3 size decreasing functions (listed above.)
.TP
.B WinKey\-l
Increase size of the master area.
.TP
.B WinKey\-Shift\-l
Increase size of windowd in the master area.
.TP
.B WinKey\-Control\-l
Increase size of windows in the stack area.
.TP
.B WinKey\-Control\-Shift\-l
Execute all 3 size increasing functions (listed above.)
.SS Tag functions
.TP
.B WinKey\-[1..9]
View windows tagged with nth tag.
.TP
.B WinKey\-Shift\-[1..9]
Tag the focused window with nth tag.
.TP
.B WinKey\-Control\-[1..9]
View/remove all windows tagged with nth tag.
.TP
.B WinKey\-Control\-Shift\-[1..9]
Apply nth tag to the focused window in addition to the tag(s) already applied to it.
.TP
.B WinKey\-0
View all tags together.
.TP
.B WinKey\-Shift\-0
Tag the focused window with all tags.
.TP
.B WinKey\-Tab
Toggle to last selected tags.
.TP
.B WinKey\-Shift\-Tab
Toggle to tag on the right of the currently selected.
.TP
.B WinKey\-Control\-Tab
Toggle to tag on the left of the currently selected.
.TP
.B WinKey\-v
Toggle 'view on tag' function (view the tag window was tagged with.)
.SS Monitor functions
.TP
.B WinKey\-,
Focus previous monitor.
.TP
.B WinKey\-Shift\-,
Tag previous monitor.
.TP
.B WinKey\-.
Focus next monitor.
.TP
.B WinKey\-Shift\-.
Tag next monitor
.SS Cosmetic functions
.TP
.B WinKey\-b
Toggle bars on the selected screen.
.TP
.B WinKey\-Shift\-b
Toggle main bar on the selected screen.
.TP
.B WinKey\-Control\-b
Toggle extra bar on the selected screen.
.TP
.B WinKey\-Control\-Shift\-b
Swap bar positions.
.TP
.B WinKey\-t
Toggle between tags appearances on the selected screen.
.TP
.B WinKey\-Shift\-t
Hide vacant tags on the selected screen.
.TP
.B WinKey\-Shift\-p
Increase window border size on the selected screen.
.TP
.B WinKey\-Control\-p
Decrease window border size on the selected screen.
.TP
.B WinKey\-Control\-Shift\-p
Set window border size to default on the selected screen.
.TP
.B WinKey\-i
Toggle gaps in 'monocle' layout on the selected screen.
.TP
.B WinKey\-Shift\-i
Increase size of inner gaps on the selected screen.
.TP
.B WinKey\-Control\-i
Decrease size of inner gaps on the selected screen.
.TP
.B WinKey\-Control\-Shift\-i
Set size of inner gaps to default on the selected screen.
.TP
.B WinKey\-i
Toggle gaps in 'tiled' layout when only 1 window is visible on the selected screen.
.TP
.B WinKey\-Shift\-i
Increase size of outer gaps on the selected screen.
.TP
.B WinKey\-Control\-i
Decrease size of outer gaps on the selected screen.
.TP
.B WinKey\-Control\-Shift\-i
Set size of outer gaps to default on the selected screen.
.SH USAGE(Mouse)
.SS Tags
.TP
.B Button1
View windows tagged with the selected tag.
.TP
.B Button3
View/remove all windows tagged with the selected tag.
.TP
.B WinKey\-Button1
Tag the focused window with the selected tag.
.TP
.B WinKey\-Button3
Apply the selected tag to the focused window in addition to the tag(s) already applied to it.
.SS User@Hostname
.TP
.B Button1
Spawn
.BR st(1).
.TP
.B Button3
Spawn
.BR neofetch(1).
.SS Window title
.TP
.B -Button1
Spawn
.BR Scratchpad.
.TP
.B -Button3
Spawn
.BR dmenu(1)
for launching other programs.
.SS Attach direction
.TP
.B Button1
Toggle next 'attach direction.'
.TP
.B Button2
Set 'attach direction' to default.
.TP
.B Button3
Toggle previous 'attach direction.'
.SS Layout symbol
.TP
.B Button1
Toggle next layout.
.TP
.B Button2
Toggle floating layout.
.TP
.B Button3
Toggle previous layout.
.SS Keyboard layout
.TP
.B Button1
Open manual page for
.BR setxkbmap(1).
.SS Keyboard shortcuts
.TP
.B Button1
Open manual page for
.BR dwm(1).
.TP
.B Button3
Open manual page for
.BR dmenu(1).
.SS Warp pointer
.TP
.B Button1
Toggle 'warp on focus.'
.SS View on tag
.TP
.B Button1
Toggle 'view on tag' function (view the tag window was tagged with.)
.SS Keyboard lock
.TP
.B Button1
Toggle 'Keyboard lock.'
.SS Power
.TP
.B Button1
Open 'shutdown' menu.
.SS Window
.TP
.B WinKey\-Button1
Move focused window while dragging. Tiled windows will be toggled to the floating state.
.TP
.B WinKey\-Button2
Toggles focused window between floating and tiled state.
.TP
.B WinKey\-Button3
Resize focused window while dragging. Tiled windows will be toggled to the floating state.
.SS Extra bar
.TP
.B WinKey\-Button1
Open manual page for
.BR xsetroot(1).
.SH CUSTOMIZATION
DWM is customized by creating a custom config.h and (re)compiling the source
code. This keeps it fast, secure and simple.
.SH SEE ALSO
.BR dmenu (1),
.BR st (1)
.SH ISSUES
.SS Java
Java applications which use the XToolkit/XAWT backend may draw grey windows
only. The XToolkit/XAWT backend breaks ICCCM-compliance in recent JDK 1.5 and early
JDK 1.6 versions, because it assumes a reparenting window manager. Possible workarounds
are using JDK 1.4 (which doesn't contain the XToolkit/XAWT backend) or setting the
environment variable
.BR AWT_TOOLKIT=MToolkit
(to use the older Motif backend instead) or running
.B xprop -root -f _NET_WM_NAME 32a -set _NET_WM_NAME LG3D
or
.B wmname LG3D
(to pretend that a non-reparenting window manager is running that the
XToolkit/XAWT backend can recognize) or when using OpenJDK setting the environment variable
.BR _JAVA_AWT_WM_NONREPARENTING=1 .
.SS Possible multi-monitor issues
Although all DWM functions support multi-monitor setups, due to lack of testing there might
be some (easily fixable) unexpected behaviour issues with multi-monitor setups.
.SH BUGS
Open issue on Github page with a detailed description and how to repplicate the bug or
send the bug report with a patch to miskuzius at gmail dot com.
